TargetFrame:ClearAllPoints()
TargetFrame:SetPoint("CENTER",UIParent,320,-180)
TargetFrame:SetUserPlaced(true)
PlayerFrame:ClearAllPoints()
PlayerFrame:SetPoint("CENTER",UIParent,-320,-180)
PlayerFrame:SetUserPlaced(true)